baseurl = "https://gogolok.github.io/"
title = "gogolok"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[params]
    author = "Robert Gogolok"
    description = "Robert Gogolok's personal website"
    keywords = "blog,developer,personal"
    info = "Platform Engineer and Dad"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/gogolok/blog/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/gogolok/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-2x fa-gitlab"
    weight = 2
    url = "https://gitlab.com/gogolok/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 3
  url = "https://fosstodon.org/@gogo"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    weight = 4
    url = "https://twitter.com/gogolok/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/robertgogolok/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-2x fa-rss"
    weight = 6
    url = "https://gogolok.github.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Impressum"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Now"
            weight = 2
            url = "now/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 3
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 4
            url = "projects/"
